[package]
name = "xcf"
version = "0.2.0"
authors = ["shivshank"]
description = "A basic standalone GIMP XCF library in Rust."

license = "Unlicense"
readme = "README.md"

keywords = ["gimp"]
repository = "https://github.com/shivshank/xcf-rs"

[dependencies]
derive-error = "0.0.4"
byteorder = "1"
